version: "2.0"
services:


  postgres:
    build:
      context: postgres
    image: postgres_image
    container_name: postgres-container
    #    ports:
    #      - "5432:5432"
    env_file:
      - postgres/.env


  backend:
    build:
      context: Password-Keeper-API
    container_name: pk-api
    env_file:
      - Password-Keeper-API/.env
    #    ports:
    #      - "8080:8080"
    depends_on:
      - postgres


  frontend:
    build:
      context: Password-Keeper-WebApp
    container_name: pk-web-app
  #    ports:
  #      - "3000:3000"


  nginx:
    build:
      context: nginx
    container_name: pk-proxy
    ports:
      - "443:443"
      - "4430:4430"
    depends_on:
      - backend
      - frontend